name: ItemSlotMachine
version: ${version}
authors: [DarkBlade12, kubotan, tash087]
website: https://github.com/gorogoro-space/ItemSlotMachine
main: com.darkblade12.itemslotmachine.ItemSlotMachine
api-version: '1.21.11'
softdepend: [Vault, Multiverse-Core, Multiworld, PlotMe, MyWorlds, Essentials, CapsuleToy]

commands:
  design:
    description: Commands related to designs
    usage: /<command> help
    aliases: [slotdesign, sd]
  coin:
    description: Commands related to coins
    usage: /<command> help
    aliases: [slotcoin, sc]
  slot:
    description: Commands related to slot machines
    usage: /<command> help
    aliases: [slotmachine, sm]
  statistic:
    description: Commands related to statistics
    usage: /<command> help
    aliases: [slotstatistic, stat, stats]

permissions:
  itemslotmachine.slot.use:
    description: Allows to use slot machines
    default: true
